name: Tagged Release to Nuget.org

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag
      id: extract_tag
      run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

    - name: Convert repository name to lowercase
      id: to_lowercase
      run: echo "::set-output name=lower_repo::${{ github.repository | toJSON | fromJSON | toLowerCase }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.to_lowercase.outputs.lower_repo }}:${{ steps.extract_tag.outputs.tag }}